
package my.webservice.com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightHandler", targetNamespace = "my.webservice.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightHandler {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightsDepartures", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlightsDepartures")
    @ResponseWrapper(localName = "getFlightsDeparturesResponse", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlightsDeparturesResponse")
    @Action(input = "my.webservice.com/FlightHandler/getFlightsDeparturesRequest", output = "my.webservice.com/FlightHandler/getFlightsDeparturesResponse")
    public List<String> getFlightsDepartures(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightsDestination", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlightsDestination")
    @ResponseWrapper(localName = "getFlightsDestinationResponse", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlightsDestinationResponse")
    @Action(input = "my.webservice.com/FlightHandler/getFlightsDestinationRequest", output = "my.webservice.com/FlightHandler/getFlightsDestinationResponse")
    public List<String> getFlightsDestination(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlight", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlight")
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "my.webservice.com", className = "my.webservice.com.GetFlightResponse")
    @Action(input = "my.webservice.com/FlightHandler/getFlightRequest", output = "my.webservice.com/FlightHandler/getFlightResponse")
    public List<String> getFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
