
package my.webservice.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightHandlerService", targetNamespace = "my.webservice.com", wsdlLocation = "http://localhost:1002/Flight?wsdl")
public class FlightHandlerService
    extends Service
{

    private final static URL FLIGHTHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTHANDLERSERVICE_EXCEPTION;
    private final static QName FLIGHTHANDLERSERVICE_QNAME = new QName("my.webservice.com", "FlightHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1002/Flight?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTHANDLERSERVICE_WSDL_LOCATION = url;
        FLIGHTHANDLERSERVICE_EXCEPTION = e;
    }

    public FlightHandlerService() {
        super(__getWsdlLocation(), FLIGHTHANDLERSERVICE_QNAME);
    }

    public FlightHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTHANDLERSERVICE_QNAME, features);
    }

    public FlightHandlerService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTHANDLERSERVICE_QNAME);
    }

    public FlightHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTHANDLERSERVICE_QNAME, features);
    }

    public FlightHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightHandler
     */
    @WebEndpoint(name = "FlightHandlerPort")
    public FlightHandler getFlightHandlerPort() {
        return super.getPort(new QName("my.webservice.com", "FlightHandlerPort"), FlightHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightHandler
     */
    @WebEndpoint(name = "FlightHandlerPort")
    public FlightHandler getFlightHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("my.webservice.com", "FlightHandlerPort"), FlightHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTHANDLERSERVICE_EXCEPTION!= null) {
            throw FLIGHTHANDLERSERVICE_EXCEPTION;
        }
        return FLIGHTHANDLERSERVICE_WSDL_LOCATION;
    }

}
