
package service.itinerary.com.Flight;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FlightDoesNotExistException", targetNamespace = "http://www.flightservice.com")
public class FlightDoesNotExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FlightDoesNotExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FlightDoesNotExistException_Exception(String message, FlightDoesNotExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FlightDoesNotExistException_Exception(String message, FlightDoesNotExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.itinerary.com.Flight.FlightDoesNotExistException
     */
    public FlightDoesNotExistException getFaultInfo() {
        return faultInfo;
    }

}
