
package com.service.Itinerary;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItineraryService", targetNamespace = "http://www.itineraryservice.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItineraryService {


    /**
     * 
     * @param destinationCity
     * @param departureCity
     * @return
     *     returns java.util.List<com.service.Itinerary.Itinerary>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItinerary", targetNamespace = "http://www.itineraryservice.com", className = "com.service.Itinerary.GetItinerary")
    @ResponseWrapper(localName = "getItineraryResponse", targetNamespace = "http://www.itineraryservice.com", className = "com.service.Itinerary.GetItineraryResponse")
    @Action(input = "http://www.itineraryservice.com/ItineraryService/getItineraryRequest", output = "http://www.itineraryservice.com/ItineraryService/getItineraryResponse")
    public List<Itinerary> getItinerary(
        @WebParam(name = "departureCity", targetNamespace = "")
        String departureCity,
        @WebParam(name = "destinationCity", targetNamespace = "")
        String destinationCity);

    /**
     * 
     * @param destinationCity
     * @param departureCity
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://www.itineraryservice.com", className = "com.service.Itinerary.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://www.itineraryservice.com", className = "com.service.Itinerary.CheckAvailabilityResponse")
    @Action(input = "http://www.itineraryservice.com/ItineraryService/checkAvailabilityRequest", output = "http://www.itineraryservice.com/ItineraryService/checkAvailabilityResponse")
    public int checkAvailability(
        @WebParam(name = "departureCity", targetNamespace = "")
        String departureCity,
        @WebParam(name = "destinationCity", targetNamespace = "")
        String destinationCity);

}
