
package com.service.booking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Booking_implService", targetNamespace = "http://booking.service/", wsdlLocation = "http://0.0.0.0:10004/Booking?wsdl")
public class BookingImplService
    extends Service
{

    private final static URL BOOKINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGIMPLSERVICE_EXCEPTION;
    private final static QName BOOKINGIMPLSERVICE_QNAME = new QName("http://booking.service/", "Booking_implService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:10004/Booking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGIMPLSERVICE_WSDL_LOCATION = url;
        BOOKINGIMPLSERVICE_EXCEPTION = e;
    }

    public BookingImplService() {
        super(__getWsdlLocation(), BOOKINGIMPLSERVICE_QNAME);
    }

    public BookingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGIMPLSERVICE_QNAME, features);
    }

    public BookingImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGIMPLSERVICE_QNAME);
    }

    public BookingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGIMPLSERVICE_QNAME, features);
    }

    public BookingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingImpl
     */
    @WebEndpoint(name = "Booking_implPort")
    public BookingImpl getBookingImplPort() {
        return super.getPort(new QName("http://booking.service/", "Booking_implPort"), BookingImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingImpl
     */
    @WebEndpoint(name = "Booking_implPort")
    public BookingImpl getBookingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booking.service/", "Booking_implPort"), BookingImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKINGIMPLSERVICE_EXCEPTION;
        }
        return BOOKINGIMPLSERVICE_WSDL_LOCATION;
    }

}
