
package my.webservice.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Auth", targetNamespace = "my.webservice.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Auth {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "my.webservice.com", className = "my.webservice.com.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "my.webservice.com", className = "my.webservice.com.AuthenticateResponse")
    @Action(input = "my.webservice.com/Auth/authenticateRequest", output = "my.webservice.com/Auth/authenticateResponse")
    public String authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
