
package service.booking.com.authenticator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticatorService", targetNamespace = "http://authentication.service/", wsdlLocation = "http://0.0.0.0:10000/Auth?wsdl")
public class AuthenticatorService
    extends Service
{

    private final static URL AUTHENTICATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATORSERVICE_EXCEPTION;
    private final static QName AUTHENTICATORSERVICE_QNAME = new QName("http://authentication.service/", "AuthenticatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:10000/Auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATORSERVICE_WSDL_LOCATION = url;
        AUTHENTICATORSERVICE_EXCEPTION = e;
    }

    public AuthenticatorService() {
        super(__getWsdlLocation(), AUTHENTICATORSERVICE_QNAME);
    }

    public AuthenticatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATORSERVICE_QNAME, features);
    }

    public AuthenticatorService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATORSERVICE_QNAME);
    }

    public AuthenticatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATORSERVICE_QNAME, features);
    }

    public AuthenticatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Authenticator
     */
    @WebEndpoint(name = "AuthenticatorPort")
    public Authenticator getAuthenticatorPort() {
        return super.getPort(new QName("http://authentication.service/", "AuthenticatorPort"), Authenticator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authenticator
     */
    @WebEndpoint(name = "AuthenticatorPort")
    public Authenticator getAuthenticatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://authentication.service/", "AuthenticatorPort"), Authenticator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATORSERVICE_EXCEPTION!= null) {
            throw AUTHENTICATORSERVICE_EXCEPTION;
        }
        return AUTHENTICATORSERVICE_WSDL_LOCATION;
    }

}
