
package com.bankservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotAuthenticatedException", targetNamespace = "http://www.bankservice.com")
public class NotAuthenticatedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotAuthenticatedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotAuthenticatedException_Exception(String message, NotAuthenticatedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotAuthenticatedException_Exception(String message, NotAuthenticatedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bankservice.NotAuthenticatedException
     */
    public NotAuthenticatedException getFaultInfo() {
        return faultInfo;
    }

}
