
package service.booking.com.itinerary;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ItineraryNotAvailable", targetNamespace = "http://www.itineraryservice.com")
public class ItineraryNotAvailable_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ItineraryNotAvailable faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ItineraryNotAvailable_Exception(String message, ItineraryNotAvailable faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ItineraryNotAvailable_Exception(String message, ItineraryNotAvailable faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.booking.com.itinerary.ItineraryNotAvailable
     */
    public ItineraryNotAvailable getFaultInfo() {
        return faultInfo;
    }

}
