
package com.authenticator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Authenticator", targetNamespace = "http://www.authenticator.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Authenticator {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.authenticator.AuthTicket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://www.authenticator.com", className = "com.authenticator.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://www.authenticator.com", className = "com.authenticator.AuthenticateResponse")
    public AuthTicket authenticate(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param ticket
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateTicket", targetNamespace = "http://www.authenticator.com", className = "com.authenticator.ValidateTicket")
    @ResponseWrapper(localName = "validateTicketResponse", targetNamespace = "http://www.authenticator.com", className = "com.authenticator.ValidateTicketResponse")
    public boolean validateTicket(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "ticket", targetNamespace = "")
        int ticket);

}
